### PR TITLE
added requirements.txt

### PR DESCRIPTION
**Pull request by CodeVINCI**
as per the easiest issue.

### CODE REVIEW

**Comment by nikhilkumarsingh** [comment]
How did you create this requirements.txt file?
It should contain only these dependencies with their latest versions: https://github.com/nikhilkumarsingh/gnewsclient/blob/f535f6c06390a6c9622f451b90d5237714ca5f7b/setup.py#L34

**Comment by CodeVINCI** [comment]
I created a new virtual enviroment to run the gnewsclient in, then i tried the given commands in readme the errors it showed me i just pip installed them and used pip freeze > requirements.txt

**Comment by CodeVINCI** [comment]
I am using it in python 2.7

**Comment by CodeVINCI** [comment]
If it's a bad request you can close it and i'll work it out again.
no problem.

**Comment by nikhilkumarsingh** [comment]
All you have to do is to put the latest versions of the install-requires list (which I shared above) in the requirements.txt file. We need to mention only top-level dependencies in the file.

Simply put 
- bs4
- requests
- html5lib

in the file.

**Comment by CodeVINCI** [comment]
i think this should work.

**Comment by CodeVINCI** [comment]
Sir can i know if this request is good/bad.

**Pull request closed without merging**
