### PR TITLE
solved #17

### PR DESCRIPTION
**Pull request by utkarshkvs1**
#17 
#2 
please review @nikhilkumarsingh

### CODE REVIEW

**Comment by Shrey97** [comment]
The GUI thing is done almost, we can work more by adding article full-text after #15 is solved.

**Comment by nikhilkumarsingh** [comment]
Font can be made large for news stories. Try to add a logo for the Tkinter application.

**Comment by nikhilkumarsingh** [comment]
Good job @Shrey97 and @utkarshkvs1 ! Now, try to make suitable changes to setup.py to ensure that GUI can be opened in a single command from terminal, just like current CLI.

**Comment by Shrey97** [comment]
Okay @nikhilkumarsingh sir, I have added the command `gnews-gui` which launches the GUI, and the older CLI version is also active.

**Comment by nikhilkumarsingh** [comment]
Why have you added those gif files?

**Comment by Shrey97** [comment]
Oh gif files should be in the gitignore file, those are downloaded when the news is loaded.

**Pull request merged**
