### PR TITLE
meta data and text extraction from each article

### PR DESCRIPTION
**Pull request by CodeVINCI**

### CODE REVIEW

**Comment by CodeVINCI** [comment]
sir if you guide me a bit i would really be able to put better efforts.

**Comment by nikhilkumarsingh** [comment]
Hi Abhishek! I'm a bit down with fever for last few days. I will try to
look into your pull request very soon.

**Comment by CodeVINCI** [comment]
okay i am sorry sir , that is fine

**Comment by nikhilkumarsingh** [comment]
I went through your code. There are a few changes required. You need to create a child class of newspaper's Article class and return a list of those articles when .get_news() is called.
In the child class you can make some utility functions so that fulltext or other metadata can be fetched easily.

**Comment by nikhilkumarsingh** [comment]
Check out the current gnewsclient and make it compatible with your code.

**Pull request closed without merging**
